Traceback (most recent call last):
  File "/opt/luftsachsen/Luftqualitaet-src/AirImport/importer.py", line 148, in get_csv_data
    'n. def.', '').replace(',', '.').replace(
  File "/opt/luftsachsen/Luftqualitaet-src/AirImport/importer.py", line 161, in _get_string
    response.raise_for_status()
  File "/opt/luftsachsen/venv/lib/python3.4/site-packages/requests/models.py", line 862, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: http://www.umwelt.sachsen.de/umwelt/infosysteme/luftonline/recherche.aspx
